"""empty message

Revision ID: 6a32cdec4073
Revises: 
Create Date: 2024-02-17 23:52:42.400650

"""
from alembic import op
import sqlalchemy as sa

import os
# get current directory
current_dir = os.path.dirname(os.path.abspath(__file__))


# revision identifiers, used by Alembic.
revision = '6a32cdec4073'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('display_name', sa.String(length=180), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_super_user', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    seed = os.path.join(current_dir, '..', 'seed')
    with open("/".join([seed, 'user.txt']), "r") as user_query:
        op.execute(f"{user_query.read()}")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
